### PR TITLE
Fix case sensitivity in CloneWorkspaceMappings

### PR DESCRIPTION
**Pull request by yingang**
please see the closed issue #26 for detailed description to the fix.

### CODE REVIEW

**Comment by mikefourie** [comment]
Hi, so if i'm reading this right, you have builds in which people have made a lot of inconsistent changes with regards to casing and when you clone, you get unexpected results because of this. are you using the 2013 or 2015 extension? are you using this fix to actually 'clean' your defs?

**Comment by yingang** [comment]
@mikefourie,
1. yes, for example, our trunk branch is $/***/MAIN now while it used to be $/***/Main
2. we are using 2013 extension -- actually we hope to use 2010 extension, but failed to find a good way to build a 2010 extension from the current code base
3. we are currently using the fix to the branch cloning (also with some other modifications -- these are just for our company)

**Comment by yingang** [comment]
@mikefourie,

I'm wondering if the PR would be accepted or not? IMHO, the original code already considered the case issue (used StringComparison.OrdinalIgnoreCase in StartsWith call) but didn't consider it in the Replace call?

**Comment by mikefourie-zz** [comment]
merged. thanks .i'll look at getting it to the 2015 branch

**Pull request merged**
